[tool.poetry]
name = "poeblix"
version = "1.0.0"
description = "Poetry plugin that adds support for building wheel files using the poetry.lock file, and data_files just like in setup.py"
authors = ["spoorn <spookump@gmail.com>"]
packages = [
    { include = "poeblix", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
# TODO: use release version when 1.2+ is officially out
poetry = "^1.2.0b1"

[tool.poetry.group.dev.dependencies]
flake8 = "*"
pre-commit = "*"

[tool.poetry.plugins."poetry.application.plugin"]
# This must be the same as the package name due to https://github.com/python-poetry/poetry/pull/5412#issuecomment-1089978391
poeblix = "poeblix.plugins:BlixPlugin"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
